config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  
  devise_for :users 
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  get 'home/about'
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
         
  end

  def about
  
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Doc's", root_path, class:"navbar-brand" %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.user_role == 0 %>
            <li class="nav-item">
              <%= link_to "Patients", patients_path, class:"nav-link" %>
            </li>
          <% end %>
          <% if current_user.user_role != 2 %>
            <li class="nav-item">
              <%= link_to "Doctors", doctors_path, class:"nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Appointments", appointments_path, class:"nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "About", home_about_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
    <form class="d-flex" role="search">
      <% if user_signed_in? %>
        <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-outline-warning m-2" %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"btn btn-outline-danger m-2" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class:"btn btn-primary m-2" %>
        <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success m-2" %>
      <% end %>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <h2>Created by:</h2>   
    <div class="card"  style="width: 30rem;">
        <h1 class="card-header text-center">Artem Buhaiov</h1>
        <div class="card-body">
        <ul class="list-group list-group-flush text-center">
            <li class="list-group-item h5"><strong><a href = "mailto: salagonfiza4@gmail.com" class="link-dark text-decoration-none">salagonfiza4@gmail.com</a></strong></li>
            <li class="list-group-item h5"><strong><a href = "tel:+380937867693" class="link-dark text-decoration-none">+380937867693</strong></li>
        </ul>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <h1>Hello!</h1>
    <% if user_signed_in? %>
        <div class="card" style="width: 30rem;">
            <h1 class="card-header text-center"><%= current_user.user_role == 0 ? "Admin" : current_user.user_role == 1 ? "Patient" : "Doctor" %></h1>
            <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Email: </strong><%= current_user.email %></li>
                <li class="list-group-item"><strong>Phone: </strong><%= current_user.phone %></li>
                <% if current_user.user_role == 0 %>
                <li class="list-group-item"><strong>Doctor ID:</strong><%= current_user.id %></li>
                <% end %>
            </ul>
            </div>
        </div>
    <% else %>
        <h3 class="text-center">Wanna try? <br/> <%= link_to "Sign In", new_user_session_path, class:"btn btn-primary btn-lg m-2" %> <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success btn-lg m-2" %></h3>
    <% end %>
</div>