config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  
  devise_for :users 
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  get 'home/about'
  root 'home#index'
end

app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :user
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_user

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    # @patient = Patient.new
    @patient = current_user.patients.build
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    # @patient = Patient.new(patient_params)
    @patient = current_user.patients.build(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to current_user.user_role == 0 ? patients_url : "", notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :phone, :email, :user_id)
    end

    def check_user
      if (current_user.user_role == 1 && current_user.patients.find_by(email: current_user.email) != nil) || current_user.user_role == 2
        redirect_to ""
      end
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name,
      class:"form-control", 
      placeholder:"First name" %>
    <br/>
    <%= form.text_field :last_name,
      class:"form-control", 
      placeholder:"Last name" %>
    
    <% if current_user.user_role == 0 %>
      <br/>
      <%= form.number_field :user_id,
        class:"form-control",
      placeholder:"User ID" %>
      <br/>
      <%= form.text_field :email,
        class:"form-control",
      placeholder:"Email" %>
      <br/>
      <%= form.text_field :phone,
        class:"form-control",
      placeholder:"Phone" %>
    <% else %>
      <%= form.number_field :user_id,
        value: current_user.id, hidden: true %>
      <%= form.text_field :email,
        value: current_user.email, hidden: true %>
      <%= form.text_field :phone,
        value: current_user.phone, hidden: true %>
    <% end %>
  </div>

  <br/>
  <div  class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>" style="display: flex; align-items: center; justify-content: center;">
  <div class="card" style="width: 30rem;">
    <h1 class="card-header text-center"><%= patient.first_name + " " + patient.last_name %></h1>
    <div class="card-body">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Phone: </strong><%= patient.phone %></li>
        <li class="list-group-item"><strong>Email: </strong><%= patient.email %></li>
      </ul>
    </div>
  </div>
</div>

app/views/patients/edit.html.erb
<div class="card">
  <h2 class="card-header">Editing patient</h2>
  <div class="card-body">
    <%= render "form", patient: @patient %>
    <br>
    <div>
      <%= link_to "Back", @patient, class:"btn btn-warning" %>
    </div>
  </div>
</div>

app/views/patients/index.html.erb
<h1>Patients List</h1>
<table class="table table-secondary table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <% if current_user.user_role == 0 %>
        <th>ID:</th>
        <th>User ID:</th>
      <% end %>
    </tr>
  <thead>

  <tbody>
    <% @patients.each do |patient| %>
      <% if current_user.user_role == 0 %>
        <tr class="card-text" style="transform: rotate(0);">
          <td><strong><%= link_to patient.first_name + " " + patient.last_name, patient, class:"link-dark stretched-link text-decoration-none" %></strong></td>
          <td><%= patient.phone %></td>
          <td><%= patient.email %></td>
          <% if current_user.user_role == 0 %>
            <th><%= patient.id %></th>
            <th><%= patient.user_id %></th>
          <% end %>
        </tr>
      <% end %>
    <% end %>
    <% if current_user.user_role == 0 %>
      <tr class="card-text text-center" style="transform: rotate(0);"><td colspan=<%= 5 - current_user.user_role %>><strong><%= link_to "Create patient", new_patient_path, class:"h4 link-dark stretched-link text-decoration-none"%></strong></td></tr>
    <% end %>
  </tbody>
</table>

<style>
table {
  border-collapse:separate;
  border:solid 5px;
  border-radius:10px;
}

th, td {
  border-radius:5px;
}
</style>

app/views/patients/new.html.erb
<div class="card">
  <h2 class="card-header">New patient</h2>
  <div class="card-body">
    <%= render "form", patient: @patient %>
    <br/>
    <%= link_to "Back to patients", patients_path, class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/patients/show.html.erb
<%= render @patient %>

<div class="btn-toolbar" role="toolbar" style="display: flex; align-items: center; justify-content: center;">
  <%= link_to "Back to patients", patients_path, class:"m-1 btn btn-primary" %>
  <% if current_user.user_role == 0 %>
  <%= link_to "Edit", edit_patient_path(@patient), class:" m-1 btn btn-outline-warning" %>
  <%= button_to "Delete", @patient, method: :delete, class:" m-1 btn btn-outline-danger" %>
  <% end %>
</div>