config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  
  devise_for :users 
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  get 'home/about'
  root 'home#index'
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    belongs_to :user
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_user
  before_action :is_patient, except: [:index, :show]
  
  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1 or /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    # @doctor = Doctor.new
    @doctor = current_user.doctors.build
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors or /doctors.json
  def create
    # @doctor = Doctor.new(doctor_params)
    @doctor = current_user.doctors.build(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to current_user.user_role == 0 ? doctors_url : "", notice: "Doctor was successfully created." }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully updated." }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:user_id, :first_name, :last_name, :phone, :email, :post,  :price, :free)
    end

    def check_user
      if current_user.user_role == 2 && current_user.doctors.find_by(email: current_user.email) != nil
        redirect_to ""
      end
    end

    def is_patient
      if current_user.user_role == 1
        redirect_to ""
      end
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_doctor.html.erb
<div id="<%= dom_id doctor %>" style="display: flex; align-items: center; justify-content: center;">
  <div class="card" style="width: 30rem;">
    <h1 class="card-header text-center"><%= doctor.first_name + " " + doctor.last_name %></h1>
    <div class="card-body">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Phone: </strong><%= doctor.phone %></li>
        <li class="list-group-item"><strong>Email: </strong><%= doctor.email %></li>
        <li class="list-group-item"><strong>Price: </strong><%= doctor.price %></li>
        <li class="list-group-item"><strong>Post: </strong><%= doctor.post %></li>
        <% if current_user.user_role == 0 %>
          <li class="list-group-item"><strong>Doctor ID:</strong><%= doctor.id %></li>
          <li class="list-group-item"><strong>Free:</strong><%= doctor.free %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, html: { :id => "doctor" }) do |form| %>
  <% if doctor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name,
      class:"form-control", 
      placeholder:"First name" %>
    <br/>
    <%= form.text_field :last_name,
      class:"form-control", 
      placeholder:"Last name" %>
    <br/>
    <%= form.number_field :price,
      class:"form-control", 
      placeholder:"Service Price",
      min:"0" %>
    <br/>
    <%= form.text_field :post,
      class:"form-control", 
      placeholder:"Your post" %>
    
    <% if current_user.user_role == 0 %>
      <br/>
      <%= form.check_box :free,
        class:"form-check-input" %>      
      <%= form.label "Free",
        class:"form-check-label"%>
      <br/>
      <br/>
      <%= form.number_field :user_id,
        class:"form-control",
      placeholder:"User ID" %>
      <br/>
      <%= form.text_field :email,
        class:"form-control",
      placeholder:"Email" %>
      <br/>
      <%= form.text_field :phone,
        class:"form-control",
      placeholder:"Phone" %>
    <% else %>
      <%= form.number_field :user_id,
        value: current_user.id, hidden: true %>
      <%= form.text_field :email,
        value: current_user.email, hidden: true %>
      <%= form.text_field :phone,
        value: current_user.phone, hidden: true %>
      <%= form.check_box :free,
        checked: true, hidden: true %>

    <% end %>
  </div>
  <div class="actions">
    <br/>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<div class="card">
  <h2 class="card-header">Editing doctor</h2>
  <div class="card-body">
    <%= render "form", doctor: @doctor %>
    <br>
    <div>
      <%= link_to "Back", @doctor, class:"btn btn-warning" %>
    </div>
  </div>
</div>

app/views/doctors/index.html.erb
<h1>Doctors List</h1>
<table class="table table-secondary table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Post</th>
      <th>Price</th>
      <th>Email</th>
      <th>Phone</th>
      <% if current_user.user_role == 0 %>
        <th>ID:</th>
        <th>User ID:</th>
        <th>Free:</th>
      <% end %>
    </tr>
  <thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <% if doctor.free || current_user.user_role == 0 %>
        <tr class="card-text" style="transform: rotate(0);">
          <td><strong><%= link_to doctor.first_name + " " + doctor.last_name, doctor, class:"link-dark text-decoration-none stretched-link" %></strong></td>
          <td><%= doctor.post %></td>
          <td><%= doctor.price %></td>
          <td><%= doctor.email %></td>
          <td><%= doctor.phone %></td>
          <% if current_user.user_role == 0 %>
            <th><%= doctor.id %></th>
            <th><%= doctor.user_id %></th>
            <th><%= doctor.free %></th>
          <% end %>
        </tr>
      <% end %>
    <% end %>
    <% if current_user.user_role == 0 %>
      <tr class="card-text text-center" style="transform: rotate(0);"><td colspan=<%= 8 - current_user.user_role %>><strong><%= link_to "Create doctor", new_doctor_path, class:"h4 link-dark stretched-link text-decoration-none"%></strong></td></tr>
    <% end %>
  </tbody>
</table>

<style>
table {
  border-collapse:separate;
  border:solid 5px;
  border-radius:10px;
}

th, td {
  border-radius:5px;
}
</style>

app/views/doctors/new.html.erb
<div class="card">
  <h2 class="card-header">New Doctor</h2>
  <div class="card-body">
    <%= render "form", doctor: @doctor %>
    <br/>
    <%= link_to "Back to doctors", doctors_path, class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/doctors/show.html.erb
<div class="d-flex flex-column" style="align-items: center;">
  <%= render @doctor%>

  <% if current_user.user_role != 2 %>
    <br/>
    <%= form_for :appointment, url: "/appointments", method: "post" do |form| %>
      <div class="input-group mb-3">
        <% @show = current_user.user_role != 0 ? true : false %>
        <%= form.number_field :doctor,
          class:"form-control",
          value: @doctor.user_id, hidden: @show %>
        <%= form.number_field :patient,
          class:"form-control",
          value: current_user.id, hidden: @show %>
        <%= form.text_field :complaint,
          class:"form-control",
          placeholder:"Complaints" %>
        <%= form.check_box :is_active,
          checked: true, hidden: true %>
        <%= form.submit "Make an appointment", class:"btn btn-outline-secondary"%>
      </div>
    <% end %>
  <% end %>

  <div class="btn-toolbar" role="toolbar" style="display: flex; align-items: center; justify-content: center;">
    <%= link_to "Back to doctors", doctors_path, class:"m-1 btn btn-primary" %>
    <% if current_user.user_role == 0 %>
    <%= link_to "Edit", edit_doctor_path(@doctor), class:"m-1 btn btn-outline-warning" %>
    <%= button_to "Delete", @doctor, method: :delete, class:"m-1 btn btn-outline-danger" %>
    <% end %>
  </div>
</div>