config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  
  devise_for :users 
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  get 'home/about'
  root 'home#index'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointments_url, notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:is_active, :doctor, :patient, :complaint, :recommendation)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>" style="display: flex; align-items: center; justify-content: center;">
  <div class="card"  style="width: 30rem;">
    <h1 class="card-header text-center"><%= appointment.complaint %></h1>
    <div class="card-body">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Recommendation: </strong><%= appointment.recommendation %></li>
        <% if current_user.user_role == 0 %>
          <li class="list-group-item"><strong>Doctor ID: </strong><%= appointment.doctor %></li>
          <li class="list-group-item"><strong>Patient ID: </strong><%= appointment.patient %></li>
          <li class="list-group-item"><strong>Active: </strong><%= appointment.is_active %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.number_field :doctor,
      class:"form-control",
      placeholder:"Doctor ID" %>
    <br/>
    <%= form.number_field :patient,
      class:"form-control",
      placeholder:"Patient ID" %>
    <br/>
    <%= form.text_field :complaint,
    class:"form-control", 
    placeholder:"Complaint" %>
    <br/>
    <%= form.text_field :recommendation,
    class:"form-control", 
    placeholder:"Recommendation" %>
    <br/>
    <%= form.check_box :is_active,
      class:"form-check-input",
      checked: :is_active %>
    <%= form.label "Active",
      class:"form-check-label"%>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<div class="card">
  <h2 class="card-header">Editing appointment</h2>
  <div class="card-body">
    <%= render "form", appointment: @appointment %>
    <br>
    <div>
      <%= link_to "Back", @appointment, class:"btn btn-warning" %>
    </div>
  </div>
</div>

app/views/appointments/index.html.erb
<h1>Appointments List</h1>
<table class="table table-secondary table-hover">
  <thead class="table-dark">
    <tr>
      <th>Complaint</th>
      <th>Recommendation</th>
      <% if current_user.user_role == 0 %>
        <th>Doctor</th>
        <th>Patient</th>
        <th>ID</th>
        <th>Is active</th>
      <% end %>
    </tr>
  <thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <% if (appointment.is_active && appointment.doctor == current_user.id) || (appointment.patient == current_user.id) || current_user.user_role == 0 %>
        <tr class="card-text" style="transform: rotate(0);">
          <td><%= link_to appointment.complaint, appointment, class:"link-dark text-decoration-none stretched-link"%>
          </td>
          <td><%= appointment.recommendation %></td>
          <% if current_user.user_role == 0 %>
            <td><%= appointment.doctor %></td>
            <td><%= appointment.patient %></td>
            <td><%= appointment.id %></td>
            <td><strong><%= link_to appointment.is_active ? "True" : "False", appointment, class:"link-dark text-decoration-none stretched-link"%></strong></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
    <% if current_user.user_role == 0 %>
      <tr class="card-text text-center" style="transform: rotate(0);"><td colspan=<%= 7 - current_user.user_role %>><strong><%= link_to "Create appointment", new_appointment_path, class:"h4 link-dark stretched-link text-decoration-none"%></strong></td></tr>
    <% end %>
  </tbody>
</table>

<style>
table {
  border-collapse:separate;
  border:solid 5px;
  border-radius:10px;
}

th, td {
  border-radius:5px;
}
</style>

app/views/appointments/new.html.erb
<div class="card">
  <h2 class="card-header">New Appointment</h2>
  <div class="card-body">
    <%= render "form", appointment: @appointment %>
    <br/>
    <%= link_to "Back to appointments", appointments_path, class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/appointments/show.html.erb
<div class="d-flex flex-column" style="align-items: center;">
  <%= render @appointment %>

  <% if (current_user.user_role == 2 && @appointment.is_active) || current_user.user_role == 0 %>
    <br/>
    <%= form_for @appointment, url: "/appointments/"+@appointment.id.to_s, method: "put" do |form| %>
      <div class="input-group mb-3">
        <%= form.check_box :is_active,
          checked: false, hidden: true %>
        <%= form.text_field :recommendation,
          class:"form-control",
          placeholder:"Recommendation" %>
        <%= form.submit "Give recommendation", class:"btn btn-outline-secondary"%>
      </div>
    <% end %>
  <% end %>

  <div class="btn-toolbar" role="toolbar" style="display: flex; align-items: center; justify-content: center;">
  <%= link_to "Back to appointments", appointments_path,  class:"m-1 btn btn-primary" %>
  <% if current_user.user_role == 0 %>
  <%= link_to "Edit", edit_appointment_path(@appointment), class:" m-1 btn btn-outline-warning" %>
  <%= button_to "Delete", @appointment, method: :delete, class:" m-1 btn btn-outline-danger" %>
  <% end %>
</div>